### ISSUE TITLE
Why use blocking io inside async methods

### ISSUE THREAD

**Issue by Hellowlol** [ludeeus/pyupdate#5]
**Version of the custom_component**

**Describe the bug**
This isnt a bug but a question. ATM pyupdate seems to be using requests inside Async methods/functions. Any reason why we don’t use aiohttp?

**log**

```
Add your logs here.
```

**Comment by ludeeus** [comment]
that's easy.
I have not yet had the time and energy to change it.
it's planed, but not sure when I will be able to do it.
